# common
THINK_MODE = True
MAX_TOKEN_NUM = 128
MAX_EXPR_NUM = 60
MAX_EXPR_NUM_CNT = 5

# model
D_MODEL = 64
N_LAYER = 8
N_HEAD = 4

# train
CKPT_PATH = './ckpt/model_params.pth'
LEARNING_RATE = 1e-5
TRAINING_STEP = 10000000
TRAINING_BATCH_SIZE = 128
ROLLOUT_GROUP_SIZE = 64
N_ROLLOUT_PROCESS = 4
