THINK_MODE = False

MAX_TOKEN_NUM = 128
MAX_EXPR_NUM = 16
MAX_EXPR_NUM_CNT = 6

CKPT_PATH = './ckpt/model_params.pth'
LEARNING_RATE = 1e-5
TRAINING_STEP = 10000000
TRAINING_BATCH_SIZE = 128

N_ROLLOUT_PROCESS = 4
